-- NOTE: This file is auto generated by ./sql-generator

-- PostRepository.create
insert into
  "post" ("ownerId", "body")
values
  ($1, $2)
returning
  *

-- PostRepository.getById
select
  "post".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      count(*) as "likeCount"
    from
      "post_like"
    where
      "post_like"."postId" = "post"."id"
  ) as "likeCount",
  (
    select
      count(*) as "commentCount"
    from
      "post_comment"
    where
      "post_comment"."postId" = "post"."id"
      and "post_comment"."deletedAt" is null
  ) as "commentCount"
from
  "post"
  inner join "user" as "owner" on "owner"."id" = "post"."ownerId"
  and "owner"."deletedAt" is null
where
  "post"."id" = $1::uuid
  and "post"."deletedAt" is null

-- PostRepository.update
update "post"
set
  "body" = $1
where
  "post"."id" = $2::uuid
returning
  *

-- PostRepository.softDelete
update "post"
set
  "deletedAt" = $1
where
  "post"."id" = $2::uuid

-- PostRepository.restore
update "post"
set
  "deletedAt" = $1
where
  "post"."id" = $2::uuid

-- PostRepository.getFeed
select
  "post".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      count(*) as "likeCount"
    from
      "post_like"
    where
      "post_like"."postId" = "post"."id"
  ) as "likeCount",
  (
    select
      count(*) as "commentCount"
    from
      "post_comment"
    where
      "post_comment"."postId" = "post"."id"
      and "post_comment"."deletedAt" is null
  ) as "commentCount"
from
  "post"
  inner join "user" as "owner" on "owner"."id" = "post"."ownerId"
  and "owner"."deletedAt" is null
  left join "post_audience" as "audience" on "audience"."postId" = "post"."id"
  and "audience"."userId" = $1::uuid
  left join "partner" on "partner"."sharedById" = "post"."ownerId"
  and "partner"."sharedWithId" = $2::uuid
where
  "post"."deletedAt" is null
  and (
    "post"."ownerId" = $3
    or "post"."visibility" = 'public'
    or (
      "post"."visibility" = 'partners'
      and "partner"."sharedById" is not null
    )
    or (
      "post"."visibility" = 'specific'
      and "audience"."userId" is not null
    )
  )
order by
  "post"."createdAt" desc,
  "post"."id" desc
limit
  $4

-- PostRepository.getByAssetId
select
  "post".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post"."ownerId"
      ) as obj
  ) as "owner"
from
  "post"
  inner join "user" as "owner" on "owner"."id" = "post"."ownerId"
  and "owner"."deletedAt" is null
  left join "post_audience" as "audience" on "audience"."postId" = "post"."id"
  and "audience"."userId" = $1::uuid
  left join "partner" on "partner"."sharedById" = "post"."ownerId"
  and "partner"."sharedWithId" = $2::uuid
  inner join "post_attachment" on "post_attachment"."postId" = "post"."id"
  and "post_attachment"."assetId" = $3::uuid
where
  "post"."deletedAt" is null
  and (
    "post"."ownerId" = $4
    or "post"."visibility" = 'public'
    or (
      "post"."visibility" = 'partners'
      and "partner"."sharedById" is not null
    )
    or (
      "post"."visibility" = 'specific'
      and "audience"."userId" is not null
    )
  )
order by
  "post"."createdAt" desc,
  "post"."id" desc

-- PostRepository.getAttachments
select
  "post_attachment".*
from
  "post_attachment"
where
  "post_attachment"."postId" = $1::uuid
order by
  "post_attachment"."position" asc

-- PostRepository.setAttachments
begin
delete from "post_attachment"
where
  "post_attachment"."postId" = $1::uuid
insert into
  "post_attachment" ("postId", "assetId", "albumId", "position")
values
  ($1::uuid, $2::uuid, $3, $4)
rollback

-- PostRepository.getAudienceUserIds
select
  "post_audience"."userId"
from
  "post_audience"
where
  "post_audience"."postId" = $1::uuid

-- PostRepository.setAudience
begin
delete from "post_audience"
where
  "post_audience"."postId" = $1::uuid
insert into
  "post_audience" ("postId", "userId")
values
  ($1::uuid, $2::uuid)
rollback
