-- NOTE: This file is auto generated by ./sql-generator

-- PostRepository.getById
select
  "post".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      count(*)::int as "likeCount"
    from
      "post_like"
    where
      "post_like"."postId" = "post"."id"
  ) as "likeCount",
  (
    select
      count(*)::int as "commentCount"
    from
      "post_comment"
    where
      "post_comment"."postId" = "post"."id"
      and "post_comment"."deletedAt" is null
  ) as "commentCount"
from
  "post"
  inner join "user" as "owner" on "owner"."id" = "post"."ownerId"
  and "owner"."deletedAt" is null
where
  "post"."id" = $1::uuid
  and "post"."deletedAt" is null

-- PostRepository.softDelete
update "post"
set
  "deletedAt" = $1
where
  "post"."id" = $2::uuid

-- PostRepository.restore
update "post"
set
  "deletedAt" = $1
where
  "post"."id" = $2::uuid

-- PostRepository.getFeed
select
  "post".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      count(*)::int as "likeCount"
    from
      "post_like"
    where
      "post_like"."postId" = "post"."id"
  ) as "likeCount",
  (
    select
      count(*)::int as "commentCount"
    from
      "post_comment"
    where
      "post_comment"."postId" = "post"."id"
      and "post_comment"."deletedAt" is null
  ) as "commentCount"
from
  "post"
  inner join "user" as "owner" on "owner"."id" = "post"."ownerId"
  and "owner"."deletedAt" is null
  left join "post_audience" as "audience" on "audience"."postId" = "post"."id"
  and "audience"."userId" = $1::uuid
  left join "partner" on "partner"."sharedById" = "post"."ownerId"
  and "partner"."sharedWithId" = $2::uuid
where
  "post"."deletedAt" is null
  and (
    "post"."ownerId" = $3
    or "post"."visibility" = 'public'
    or (
      "post"."visibility" = 'partners'
      and "partner"."sharedById" is not null
    )
    or (
      "post"."visibility" = 'specific'
      and "audience"."userId" is not null
    )
  )
order by
  "post"."createdAt" desc,
  "post"."id" desc
limit
  $4

-- PostRepository.getByAssetId
select
  "post".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post"."ownerId"
      ) as obj
  ) as "owner",
  (
    select
      count(*)::int as "likeCount"
    from
      "post_like"
    where
      "post_like"."postId" = "post"."id"
  ) as "likeCount",
  (
    select
      count(*)::int as "commentCount"
    from
      "post_comment"
    where
      "post_comment"."postId" = "post"."id"
      and "post_comment"."deletedAt" is null
  ) as "commentCount"
from
  "post"
  inner join "user" as "owner" on "owner"."id" = "post"."ownerId"
  and "owner"."deletedAt" is null
  left join "post_audience" as "audience" on "audience"."postId" = "post"."id"
  and "audience"."userId" = $1::uuid
  left join "partner" on "partner"."sharedById" = "post"."ownerId"
  and "partner"."sharedWithId" = $2::uuid
  inner join "post_attachment" on "post_attachment"."postId" = "post"."id"
  and "post_attachment"."assetId" = $3::uuid
where
  "post"."deletedAt" is null
  and (
    "post"."ownerId" = $4
    or "post"."visibility" = 'public'
    or (
      "post"."visibility" = 'partners'
      and "partner"."sharedById" is not null
    )
    or (
      "post"."visibility" = 'specific'
      and "audience"."userId" is not null
    )
  )
order by
  "post"."createdAt" desc,
  "post"."id" desc

-- PostRepository.getAttachmentsForPosts
select
  "post_attachment".*
from
  "post_attachment"
where
  "post_attachment"."postId" in ($1)
order by
  "post_attachment"."postId" asc,
  "post_attachment"."position" asc

-- PostRepository.getLikedPostIds
select
  "post_like"."postId"
from
  "post_like"
where
  "post_like"."userId" = $1::uuid
  and "post_like"."postId" in ($2)

-- PostRepository.getAudienceForPosts
select
  "post_audience"."postId",
  "post_audience"."userId"
from
  "post_audience"
where
  "post_audience"."postId" in ($1)
order by
  "post_audience"."postId" asc,
  "post_audience"."userId" asc

-- PostRepository.getAttachments
select
  "post_attachment".*
from
  "post_attachment"
where
  "post_attachment"."postId" = $1::uuid
order by
  "post_attachment"."position" asc

-- PostRepository.getAudienceUserIds
select
  "post_audience"."userId"
from
  "post_audience"
where
  "post_audience"."postId" = $1::uuid
order by
  "post_audience"."userId" asc

-- PostRepository.createComment
insert into
  "post_comment" ("postId", "userId", "body", "parentId")
values
  ($1, $2, $3, $4)
returning
  *

-- PostRepository.getCommentById
select
  "post_comment".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post_comment"."userId"
      ) as obj
  ) as "user"
from
  "post_comment"
  inner join "user" as "author" on "author"."id" = "post_comment"."userId"
  and "author"."deletedAt" is null
where
  "post_comment"."id" = $1::uuid
  and "post_comment"."deletedAt" is null

-- PostRepository.getCommentsByPost
select
  "post_comment".*,
  (
    select
      to_json(obj)
    from
      (
        select
          "id",
          "name",
          "email",
          "avatarColor",
          "profileImagePath",
          "profileChangedAt"
        from
          "user"
        where
          "user"."id" = "post_comment"."userId"
      ) as obj
  ) as "user"
from
  "post_comment"
  inner join "user" as "author" on "author"."id" = "post_comment"."userId"
  and "author"."deletedAt" is null
where
  "post_comment"."postId" = $1::uuid
  and "post_comment"."deletedAt" is null
order by
  "post_comment"."createdAt" asc,
  "post_comment"."id" asc

-- PostRepository.softDeleteComment
with recursive
  "thread" ("id") as (
    select
      "post_comment"."id" as "id"
    from
      "post_comment"
    where
      "post_comment"."id" = $1::uuid
    union all
    select
      "reply"."id" as "id"
    from
      "post_comment" as "reply"
      inner join "thread" as "parent" on "parent"."id" = "reply"."parentId"
  )
update "post_comment"
set
  "deletedAt" = $2
where
  "post_comment"."id" in (
    select
      "thread"."id"
    from
      "thread"
  )

-- PostRepository.createWithDetails
begin
insert into
  "post" ("ownerId", "body", "visibility")
values
  ($1, $2, $3)
returning
  *
rollback

-- PostRepository.updateWithDetails
begin
delete from "post_attachment"
where
  "post_attachment"."postId" = $1::uuid
insert into
  "post_attachment" ("postId", "assetId", "albumId", "position")
values
  ($1::uuid, $2::uuid, $3, $4)
rollback
